from PIL import Image

def find_inner(file):
    im = Image.open(file)
    pixels = im.load()
    width, height = im.size
    
    # Let's find the first row from top that is not white
    # Wait, the image might have a white border.
    # We saw earlier that the corners are NOT white.
    # Ah! Maybe the corners are NOT white because the image is a polaroid that is slightly rotated *on a black/dark background*?
    # If the image was generated by AI, it might have drawn a rotated polaroid on a dark background!
    
    # Let's count how many white-ish pixels there are.
    white_pixels = 0
    for y in range(height):
        for x in range(width):
            p = pixels[x, y]
            if p[0] > 240 and p[1] > 240 and p[2] > 240:
                white_pixels += 1
                
    print(f"White-ish pixels: {white_pixels} out of {width*height}")
    
find_inner('public/images/browse-collections.png')
find_inner('public/images/meet-fans.png')
